const PATHS = Object.freeze({
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  PASSWORD: '/password',
  USERS: '/users',
  USERS_LIST: '/users/list',
  USERS_CREATE: '/users/create',
  USERS_EDIT: '/users/edit',
  CATEGORIES: '/categories',
  CATEGORIES_LIST: '/categories/list',
  BRANDS: '/brands',
  BRANDS_LIST: '/brands/list',
  PRODUCTS: '/products',
  PRODUCTS_LIST: '/products/list',
  PRODUCTS_CREATE: '/products/create',
  PRODUCTS_EDIT: '/products/edit',
  DISCOUNTS: '/discounts',
  DISCOUNTS_LIST: '/discounts/list',
  ORDERS: '/orders',
  INVOICES: '/invoices',
  ORDERS_LIST: '/orders/list',
  BANNERS: '/banners',
  ORDERS: '/orders',
});

export default PATHS;
